# Generated by Django 6.0.2 on 2026-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('entidade', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=60)),
            ],
        ),
    ]
