# Generated by Django 4.1 on 2026-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
