# Generated by Django 6.0.2 on 2026-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
