# Generated by Django 6.0.2 on 2026-03-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0002_alter_associado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
