# Generated by Django 6.0.2 on 2026-03-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0006_empresa_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associado',
            name='entidade',
        ),
        migrations.AddField(
            model_name='associado',
            name='fk_empresa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associado.empresa'),
        ),
    ]
